name: Deploy to Test Server (T1)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debugging
      run: echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

    - name: Deploy
      uses: appleboy/ssh-action@v2
      with:
        host: ${{ secrets.T_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          repo_name="your_repository_name"  # Replace with your actual repository name
          bash /opt/install_odoo/git_update.sh $repo_name
