name: Deploy to Test Server (T1)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debugging
      run: |
        echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}" >> $GITHUB_ENV

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.T_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          repo_name=$(echo "$GITHUB_REPOSITORY" | awk -F '/' '{print $2}')
          echo "Repository Name: $repo_name"
          bash /opt/install_odoo/git_update.sh $repo_name
