name: Deploy to Test Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "Actions"  # Set the repository name here

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.T_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          # Use the environment variable in the script
          export REPO_NAME="${REPO_NAME}"

          # Run the restart_odoo.sh script
          bash /opt/install_odoo/restart_odoo.sh
