name: Deploy to Staging Server (S1)

on:
  push:
    branches:
      - staging-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.S_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |

          # Run the git update script to update the repo
          bash /opt/install_odoo/git_update.sh Actions staging-*
